package laporan;
import fungsi.koneksiDB;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.RejectedExecutionException;
import javax.swing.SwingUtilities;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;

public class DlgRL4A extends javax.swing.JDialog {
    private final validasi Valid=new validasi();
    private final Connection koneksi=koneksiDB.condb();
    private PreparedStatement ps,ps2,ps3;
    private ResultSet rs,rs2;
    private StringBuilder htmlContent;
    private final ExecutorService executor = Executors.newSingleThreadExecutor();
    private volatile boolean ceksukses = false;
    // hitungan per kode ICD ditampung di Map, lihat isiTabel()
    
    /** Creates new form DlgProgramStudi
     * @param parent
     * @param modal */
    public DlgRL4A(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        HTMLEditorKit kit = new HTMLEditorKit();
        LoadHTML.setEditable(true);
        LoadHTML.setEditorKit(kit);
        LoadHTML1.setEditable(true);
        LoadHTML1.setEditorKit(kit);
        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule(
                ".isi td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi2 td{font: 8.5px tahoma;height:12px;background: #ffffff;color:#323232;}"+
                ".isi3 td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"
        );
        Document doc = kit.createDefaultDocument();
        LoadHTML.setDocument(doc);
        LoadHTML1.setDocument(doc);
    }
    private Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();
    private int i=0;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kd2 = new widget.TextBox();
        internalFrame1 = new widget.InternalFrame();
        panelisi1 = new widget.panelisi();
        label11 = new widget.Label();
        Tgl1 = new widget.Tanggal();
        label18 = new widget.Label();
        Tgl2 = new widget.Tanggal();
        btnCari = new widget.Button();
        label9 = new widget.Label();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();
        TabRawat = new javax.swing.JTabbedPane();
        Scroll = new widget.ScrollPane();
        LoadHTML = new widget.editorpane();
        Scroll1 = new widget.ScrollPane();
        LoadHTML1 = new widget.editorpane();

        Kd2.setName("Kd2"); // NOI18N
        Kd2.setPreferredSize(new java.awt.Dimension(207, 23));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ RL 4A Data Keadaan Morbiditas Pasien Rawat Inap ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelisi1.setName("panelisi1"); // NOI18N
        panelisi1.setPreferredSize(new java.awt.Dimension(100, 56));
        panelisi1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label11.setText("Tanggal :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(55, 23));
        panelisi1.add(label11);

        Tgl1.setDisplayFormat("dd-MM-yyyy");
        Tgl1.setName("Tgl1"); // NOI18N
        Tgl1.setPreferredSize(new java.awt.Dimension(100, 23));
        panelisi1.add(Tgl1);

        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setText("s.d.");
        label18.setName("label18"); // NOI18N
        label18.setPreferredSize(new java.awt.Dimension(30, 23));
        panelisi1.add(label18);

        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(100, 23));
        panelisi1.add(Tgl2);

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        btnCari.setMnemonic('2');
        btnCari.setToolTipText("Alt+2");
        btnCari.setName("btnCari"); // NOI18N
        btnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        btnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCariKeyPressed(evt);
            }
        });
        panelisi1.add(btnCari);

        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setName("label9"); // NOI18N
        label9.setPreferredSize(new java.awt.Dimension(100, 30));
        panelisi1.add(label9);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelisi1.add(BtnPrint);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelisi1.add(BtnKeluar);

        internalFrame1.add(panelisi1, java.awt.BorderLayout.PAGE_END);

        TabRawat.setBackground(new java.awt.Color(255, 255, 253));
        TabRawat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 246, 236)));
        TabRawat.setForeground(new java.awt.Color(50, 50, 50));
        TabRawat.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        TabRawat.setName("TabRawat"); // NOI18N
        TabRawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabRawatMouseClicked(evt);
            }
        });

        Scroll.setBorder(null);
        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        LoadHTML.setBorder(null);
        LoadHTML.setName("LoadHTML"); // NOI18N
        Scroll.setViewportView(LoadHTML);

        TabRawat.addTab("Berdasar Tanggal Masuk", Scroll);

        Scroll1.setBorder(null);
        Scroll1.setName("Scroll1"); // NOI18N
        Scroll1.setOpaque(true);

        LoadHTML1.setBorder(null);
        LoadHTML1.setName("LoadHTML1"); // NOI18N
        Scroll1.setViewportView(LoadHTML1);

        TabRawat.addTab("Berdasar Tanggal Keluar", Scroll1);

        internalFrame1.add(TabRawat, java.awt.BorderLayout.CENTER);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
private void KdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TKdKeyPressed
    Valid.pindah(evt,BtnCari,Nm);
}//GEN-LAST:event_TKdKeyPressed
*/

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            
            File g = new File("file2.css");            
            BufferedWriter bg = new BufferedWriter(new FileWriter(g));
            bg.write(
                    ".isi td{border-right: 1px solid #e2e7dd;font: 11px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                    ".isi2 td{font: 11px tahoma;height:12px;background: #ffffff;color:#323232;}"+                    
                    ".isi3 td{border-right: 1px solid #e2e7dd;font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"+
                    ".isi4 td{font: 11px tahoma;height:12px;border-top: 1px solid #e2e7dd;background: #ffffff;color:#323232;}"
            );
            bg.close();
            
            File f = new File("rl4a.html");            
            BufferedWriter bw = new BufferedWriter(new FileWriter(f));
            if(TabRawat.getSelectedIndex()==0){
                bw.write(LoadHTML.getText().replaceAll("<head>","<head><link href=\"file2.css\" rel=\"stylesheet\" type=\"text/css\" />"+
                            "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                                "<tr class='isi2'>"+
                                    "<td valign='top' align='center'>"+
                                        "<font size='4' face='Tahoma'>"+akses.getnamars()+"</font><br>"+
                                        akses.getalamatrs()+", "+akses.getkabupatenrs()+", "+akses.getpropinsirs()+"<br>"+
                                        akses.getkontakrs()+", E-mail : "+akses.getemailrs()+"<br><br>"+
                                        "<font size='2' face='Tahoma'>DATA KEADAAN MORBIDITAS PASIEN RAWAT INAP RUMAH SAKIT PENYEBAB KECELAKAN<br>PERIODE "+Tgl1.getSelectedItem()+" s.d. "+Tgl2.getSelectedItem()+"<br><br></font>"+        
                                    "</td>"+
                               "</tr>"+
                            "</table>")
                );
                bw.close();
            }else if(TabRawat.getSelectedIndex()==1){
                bw.write(LoadHTML1.getText().replaceAll("<head>","<head><link href=\"file2.css\" rel=\"stylesheet\" type=\"text/css\" />"+
                            "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                                "<tr class='isi2'>"+
                                    "<td valign='top' align='center'>"+
                                        "<font size='4' face='Tahoma'>"+akses.getnamars()+"</font><br>"+
                                        akses.getalamatrs()+", "+akses.getkabupatenrs()+", "+akses.getpropinsirs()+"<br>"+
                                        akses.getkontakrs()+", E-mail : "+akses.getemailrs()+"<br><br>"+
                                        "<font size='2' face='Tahoma'>DATA KEADAAN MORBIDITAS PASIEN RAWAT INAP RUMAH SAKIT PENYEBAB KECELAKAN<br>PERIODE "+Tgl1.getSelectedItem()+" s.d. "+Tgl2.getSelectedItem()+"<br><br></font>"+        
                                    "</td>"+
                               "</tr>"+
                            "</table>")
                );
                bw.close();
            }                
            Desktop.getDesktop().browse(f.toURI());
        } catch (Exception e) {
            System.out.println("Notifikasi : "+e);
        }     
        
        this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnPrintActionPerformed(null);
        }else{
            Valid.pindah(evt,Tgl2,BtnKeluar);
        }
    }//GEN-LAST:event_BtnPrintKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }else{Valid.pindah(evt,BtnPrint,Tgl1);}
    }//GEN-LAST:event_BtnKeluarKeyPressed

private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        if(TabRawat.getSelectedIndex()==0){
            runBackground(() ->prosesCari());
        }else if(TabRawat.getSelectedIndex()==1){
            runBackground(() ->prosesCari2());
        }
}//GEN-LAST:event_btnCariActionPerformed

private void btnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            btnCariActionPerformed(null);
        }else{
            Valid.pindah(evt, Tgl2, BtnPrint);
        }
}//GEN-LAST:event_btnCariKeyPressed

    private void TabRawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabRawatMouseClicked
        if(TabRawat.getSelectedIndex()==0){
            runBackground(() ->prosesCari());
        }else if(TabRawat.getSelectedIndex()==1){
            runBackground(() ->prosesCari2());
        }
    }//GEN-LAST:event_TabRawatMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgRL4A dialog = new DlgRL4A(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.TextBox Kd2;
    private widget.editorpane LoadHTML;
    private widget.editorpane LoadHTML1;
    private widget.ScrollPane Scroll;
    private widget.ScrollPane Scroll1;
    private javax.swing.JTabbedPane TabRawat;
    private widget.Tanggal Tgl1;
    private widget.Tanggal Tgl2;
    private widget.Button btnCari;
    private widget.InternalFrame internalFrame1;
    private widget.Label label11;
    private widget.Label label18;
    private widget.Label label9;
    private widget.panelisi panelisi1;
    // End of variables declaration//GEN-END:variables

    // ===== SIRS Revisi 6.3 : RL 4.1 Kompilasi Penyakit/Morbiditas Pasien Rawat Inap =====
    // Penyakit per kode ICD-10 (bukan kelompok DTD) dan 25 kelompok umur (lihat UmurSirs63).
    private String headerHtml(){
        StringBuilder h=new StringBuilder();
        h.append("<tr class='isi'>"+
            "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='3'>No.</td>"+
            "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='3'>Kode ICD</td>"+
            "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='3'>Diagnosis Penyakit</td>"+
            "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='"+(UmurSirs63.JML*2)+"'>Jumlah Pasien Keluar Hidup dan Mati Menurut Kelompok Umur &amp; Jenis Kelamin</td>"+
            "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='3'>Jumlah Pasien Keluar Hidup dan Mati Menurut Jenis Kelamin</td>"+
            "<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='3'>Jumlah Pasien Keluar Mati</td>"+
        "</tr>");
        h.append("<tr class='isi'>");
        for(String l : UmurSirs63.LABEL){
            h.append("<td valign='middle' bgcolor='#FFFAFA' align='center' colspan='2'>"+l+"</td>");
        }
        h.append("<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='2'>L</td>"+
                 "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='2'>P</td>"+
                 "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='2'>Total</td>"+
                 "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='2'>L</td>"+
                 "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='2'>P</td>"+
                 "<td valign='middle' bgcolor='#FFFAFA' align='center' rowspan='2'>Total</td>");
        h.append("</tr><tr class='isi'>");
        for(int g=0;g<UmurSirs63.JML;g++){
            h.append("<td valign='middle' bgcolor='#FFFAFA' align='center'>L</td>"+
                     "<td valign='middle' bgcolor='#FFFAFA' align='center'>P</td>");
        }
        h.append("</tr>");
        return h.toString();
    }

    private void prosesCari() {
        isiTabel(LoadHTML,false);
    }

    private void prosesCari2() {
        isiTabel(LoadHTML1,true);
    }

    /**
     * @param target panel HTML tujuan
     * @param basisKeluar true = berdasar tanggal keluar (sesuai SIRS 6.3 RL 4.1),
     *                    false = berdasar tanggal masuk/registrasi
     */
    private void isiTabel(widget.editorpane target, boolean basisKeluar) {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        int tanpaTglLahir=0;
        try {
            htmlContent = new StringBuilder();
            htmlContent.append(headerHtml());

            String acuan,joinExtra,filter,matiExpr;
            if(basisKeluar){
                // RL 4.1 resmi : pasien KELUAR, umur dihitung saat keluar.
                // 'Pindah Kamar' hanya perpindahan ruangan, bukan keluar RS, jadi dikecualikan
                // supaya pasien tidak terhitung berkali-kali.
                joinExtra="inner join kamar_inap on kamar_inap.no_rawat=reg_periksa.no_rawat ";
                acuan="timestamp(kamar_inap.tgl_keluar,kamar_inap.jam_keluar)";
                filter="and kamar_inap.stts_pulang<>'Pindah Kamar' and kamar_inap.tgl_keluar between ? and ? ";
                matiExpr="(kamar_inap.stts_pulang='Meninggal')";
            }else{
                // Berdasar tanggal masuk : umur dihitung saat registrasi
                joinExtra="";
                acuan="timestamp(reg_periksa.tgl_registrasi,reg_periksa.jam_reg)";
                filter="and reg_periksa.tgl_registrasi between ? and ? and reg_periksa.stts<>'Batal' ";
                matiExpr="exists(select 1 from kamar_inap ki2 where ki2.no_rawat=reg_periksa.no_rawat and ki2.stts_pulang='Meninggal')";
            }
            // jam lahir bayi dari pasien_bayi (menu Data Kelahiran Bayi) agar kelompok
            // "<1 jam" dan "1-23 jam" tepat; pasien_bayi ber-PK no_rkm_medis sehingga
            // left join ini tidak menggandakan baris
            String grp=UmurSirs63.caseUmur("pasien.tgl_lahir","ifnull(pasien_bayi.jam_lahir,'00:00:00')",acuan);

            ps=koneksi.prepareStatement(
                "select reg_periksa.no_rawat as no_rawat, diagnosa_pasien.kd_penyakit as kd, substring(penyakit.nm_penyakit,1,80) as nm, "+
                grp+" as grp, pasien.jk as jk, "+matiExpr+" as mati "+
                "from reg_periksa "+
                joinExtra+
                "inner join pasien on pasien.no_rkm_medis=reg_periksa.no_rkm_medis "+
                "left join pasien_bayi on pasien_bayi.no_rkm_medis=pasien.no_rkm_medis "+
                "inner join diagnosa_pasien on diagnosa_pasien.no_rawat=reg_periksa.no_rawat "+
                "inner join penyakit on penyakit.kd_penyakit=diagnosa_pasien.kd_penyakit "+
                // Mengikuti logika RL 4A lama : SEMUA diagnosa dihitung (utama maupun
                // sekunder), bukan hanya diagnosa utama, sehingga angkanya sebanding dengan
                // laporan lama. Konsekuensinya satu pasien bisa muncul di beberapa baris
                // penyakit, jadi total baris bisa melebihi jumlah pasien keluar.
                "where diagnosa_pasien.status='Ranap' "+
                filter+
                "order by diagnosa_pasien.kd_penyakit");

            // kd -> [0..49]=umur x L/P, [50]=mati L, [51]=mati P
            java.util.Map<String,int[]> data=new java.util.LinkedHashMap<>();
            java.util.Map<String,String> nama=new java.util.LinkedHashMap<>();
            try {
                ps.setString(1,Valid.SetTgl(Tgl1.getSelectedItem()+""));
                ps.setString(2,Valid.SetTgl(Tgl2.getSelectedItem()+""));
                rs=ps.executeQuery();
                // Satu no_rawat bisa punya lebih dari satu baris kamar_inap keluar
                // (mis. salah input), sehingga tanpa dedup pasiennya terhitung dobel.
                java.util.Set<String> sudah=new java.util.HashSet<>();
                while(rs.next()){
                    int g=rs.getInt("grp");
                    if(g<0){
                        tanpaTglLahir++;
                        continue;
                    }
                    String kd=rs.getString("kd");
                    if(!sudah.add(rs.getString("no_rawat")+"|"+kd)){
                        continue;
                    }
                    int[] a=data.get(kd);
                    if(a==null){
                        a=new int[UmurSirs63.JML*2+2];
                        data.put(kd,a);
                        nama.put(kd,rs.getString("nm")==null?"":rs.getString("nm"));
                    }
                    int sx="L".equals(rs.getString("jk"))?0:1;
                    a[g*2+sx]++;
                    if(rs.getInt("mati")==1){
                        a[UmurSirs63.JML*2+sx]++;
                    }
                }
            } catch (Exception e) {
                System.out.println("laporan.DlgRL4A.isiTabel() 1 : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }

            int[] ttl=new int[UmurSirs63.JML*2+2];
            i=1;
            for(java.util.Map.Entry<String,int[]> e : data.entrySet()){
                int[] a=e.getValue();
                int tl=0,tp=0;
                StringBuilder sel=new StringBuilder();
                for(int g=0;g<UmurSirs63.JML*2;g++){
                    sel.append("<td valign='middle' align='center'>").append(a[g]).append("</td>");
                    ttl[g]+=a[g];
                    if(g%2==0){ tl+=a[g]; }else{ tp+=a[g]; }
                }
                int ml=a[UmurSirs63.JML*2], mp=a[UmurSirs63.JML*2+1];
                ttl[UmurSirs63.JML*2]+=ml;
                ttl[UmurSirs63.JML*2+1]+=mp;
                htmlContent.append(
                    "<tr class='isi'>"+
                        "<td valign='middle' align='center'>"+i+"</td>"+
                        "<td valign='middle' align='center'>"+e.getKey()+"</td>"+
                        "<td valign='middle' align='left'>"+nama.get(e.getKey())+"</td>"+
                        sel.toString()+
                        "<td valign='middle' align='center'>"+tl+"</td>"+
                        "<td valign='middle' align='center'>"+tp+"</td>"+
                        "<td valign='middle' align='center'>"+(tl+tp)+"</td>"+
                        "<td valign='middle' align='center'>"+ml+"</td>"+
                        "<td valign='middle' align='center'>"+mp+"</td>"+
                        "<td valign='middle' align='center'>"+(ml+mp)+"</td>"+
                    "</tr>"
                );
                i++;
            }

            if(!data.isEmpty()){
                int tl=0,tp=0;
                StringBuilder sel=new StringBuilder();
                for(int g=0;g<UmurSirs63.JML*2;g++){
                    sel.append("<td valign='middle' align='center'><b>").append(ttl[g]).append("</b></td>");
                    if(g%2==0){ tl+=ttl[g]; }else{ tp+=ttl[g]; }
                }
                int ml=ttl[UmurSirs63.JML*2], mp=ttl[UmurSirs63.JML*2+1];
                htmlContent.append(
                    "<tr class='isi'>"+
                        "<td valign='middle' align='center'></td>"+
                        "<td valign='middle' align='center'></td>"+
                        "<td valign='middle' align='left'><b>TOTAL</b></td>"+
                        sel.toString()+
                        "<td valign='middle' align='center'><b>"+tl+"</b></td>"+
                        "<td valign='middle' align='center'><b>"+tp+"</b></td>"+
                        "<td valign='middle' align='center'><b>"+(tl+tp)+"</b></td>"+
                        "<td valign='middle' align='center'><b>"+ml+"</b></td>"+
                        "<td valign='middle' align='center'><b>"+mp+"</b></td>"+
                        "<td valign='middle' align='center'><b>"+(ml+mp)+"</b></td>"+
                    "</tr>"
                );
            }

            target.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
        } catch (Exception e) {
            System.out.println("laporan.DlgRL4A.isiTabel() 2 : "+e);
        }
        this.setCursor(Cursor.getDefaultCursor());
        if(tanpaTglLahir>0){
            final int n=tanpaTglLahir;
            SwingUtilities.invokeLater(() -> javax.swing.JOptionPane.showMessageDialog(null,
                "Perhatian : "+n+" data tidak dihitung karena tanggal lahir pasien kosong.\n"+
                "Silahkan lengkapi tanggal lahir pasien tersebut agar masuk laporan."));
        }
    }

    public void isCek(){
        BtnPrint.setEnabled(akses.getrl4asebab());
    }
    
    private void runBackground(Runnable task) {
        if (ceksukses) return;
        if (executor.isShutdown() || executor.isTerminated()) return;
        if (!isDisplayable()) return;

        ceksukses = true;
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        try {
            executor.submit(() -> {
                try {
                    task.run();
                } finally {
                    ceksukses = false;
                    SwingUtilities.invokeLater(() -> {
                        if (isDisplayable()) {
                            setCursor(Cursor.getDefaultCursor());
                        }
                    });
                }
            });
        } catch (RejectedExecutionException ex) {
            ceksukses = false;
        }
    }
    
    @Override
    public void dispose() {
        executor.shutdownNow();
        super.dispose();
    }
    
}
