/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgLhtBiaya.java
 *
 * Created on 12 Jul 10, 16:21:34
 */

package laporan;

import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.RejectedExecutionException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author perpustakaan
 */
public final class DlgRl32 extends javax.swing.JDialog {
    private final DefaultTableModel tabMode;
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    private final ExecutorService executor = Executors.newSingleThreadExecutor();
    private volatile boolean ceksukses = false;
    private int i=0,rujukan=0,nonrujukan=0,dirawat=0,dirujuk=0,pulang=0,
            meninggalL=0,meninggalP=0,doaL=0,doaP=0,lukaL=0,lukaP=0,
            ttlrujukan=0,ttlnonrujukan=0,ttldirawat=0,ttldirujuk=0,ttlpulang=0,
            ttlmeninggalL=0,ttlmeninggalP=0,ttldoaL=0,ttldoaP=0,ttllukaL=0,ttllukaP=0;
    /** Creates new form DlgLhtBiaya
     * @param parent
     * @param modal */
    public DlgRl32(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(8,1);
        setSize(885,674);

        Object[] rowRwJlDr={"No.","Jenis Pelayanan","Rujukan","Non Rujukan","Dirawat","Dirujuk","Pulang","Luka-luka (L)","Luka-luka (P)","Mati di IGD (L)","Mati di IGD (P)","DOA (L)","DOA (P)"};
        tabMode=new DefaultTableModel(null,rowRwJlDr){
              @Override public boolean isCellEditable(int rowIndex, int colIndex){return false;}
        };
        tbBangsal.setModel(tabMode);
        //tbBangsal.setDefaultRenderer(Object.class, new WarnaTable(jPanel2.getBackground(),tbBangsal.getBackground()));
        tbBangsal.setPreferredScrollableViewportSize(new Dimension(500,500));
        tbBangsal.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        for (i = 0; i < 13; i++) {
            TableColumn column = tbBangsal.getColumnModel().getColumn(i);
            if(i==0){
                column.setPreferredWidth(25);
            }else if(i==1){
                column.setPreferredWidth(200);
            }else{
                column.setPreferredWidth(80);
            }
        }
        tbBangsal.setDefaultRenderer(Object.class, new WarnaTable());

        TCari.setDocument(new batasInput((byte)100).getKata(TCari));
                   

        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbBangsal = new widget.Table();
        panelGlass5 = new widget.panelisi();
        label11 = new widget.Label();
        Tgl1 = new widget.Tanggal();
        label18 = new widget.Label();
        Tgl2 = new widget.Tanggal();
        jLabel6 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnAll = new widget.Button();
        jLabel7 = new widget.Label();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ RL 3.2 Kunjungan Rawat Darurat ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50,50,50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbBangsal.setName("tbBangsal"); // NOI18N
        Scroll.setViewportView(tbBangsal);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelGlass5.setName("panelGlass5"); // NOI18N
        panelGlass5.setPreferredSize(new java.awt.Dimension(55, 55));
        panelGlass5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label11.setText("Tanggal :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(50, 23));
        panelGlass5.add(label11);

        Tgl1.setDisplayFormat("dd-MM-yyyy");
        Tgl1.setName("Tgl1"); // NOI18N
        Tgl1.setPreferredSize(new java.awt.Dimension(90, 23));
        panelGlass5.add(Tgl1);

        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setText("s.d.");
        label18.setName("label18"); // NOI18N
        label18.setPreferredSize(new java.awt.Dimension(25, 23));
        panelGlass5.add(label18);

        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(90, 23));
        panelGlass5.add(Tgl2);

        jLabel6.setText("Key Word :");
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(60, 23));
        panelGlass5.add(jLabel6);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(155, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelGlass5.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('2');
        BtnCari.setToolTipText("Alt+2");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnCari);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('M');
        BtnAll.setToolTipText("Alt+M");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnAll);

        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(30, 23));
        panelGlass5.add(jLabel7);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnPrint);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnKeluar);

        internalFrame1.add(panelGlass5, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if(tabMode.getRowCount()==0){
            JOptionPane.showMessageDialog(null,"Maaf, data sudah habis. Tidak ada data yang bisa anda print...!!!!");
            //TCari.requestFocus();
        }else if(tabMode.getRowCount()!=0){
            
            Map<String, Object> param = new HashMap<>();         
            param.put("namars",akses.getnamars());
            param.put("alamatrs",akses.getalamatrs());
            param.put("kotars",akses.getkabupatenrs());
            param.put("propinsirs",akses.getpropinsirs());
            param.put("kontakrs",akses.getkontakrs());
            param.put("emailrs",akses.getemailrs());   
            param.put("periode",Tgl1.getSelectedItem()+" s.d. "+Tgl2.getSelectedItem());  
            param.put("tanggal",Tgl2.getDate());  
            param.put("logo",Sequel.cariGambar("select setting.logo from setting"));  
            Sequel.queryu("delete from temporary where temp37='"+akses.getalamatip()+"'");
            for(int r=0;r<tabMode.getRowCount();r++){ 
                if(!tbBangsal.getValueAt(r,0).toString().contains(">>")){
                    Sequel.menyimpan("temporary","'"+r+"','"+
                                    tabMode.getValueAt(r,0).toString()+"','"+
                                    tabMode.getValueAt(r,1).toString()+"','"+
                                    tabMode.getValueAt(r,2).toString()+"','"+
                                    tabMode.getValueAt(r,3).toString()+"','"+
                                    tabMode.getValueAt(r,4).toString()+"','"+
                                    tabMode.getValueAt(r,5).toString()+"','"+
                                    tabMode.getValueAt(r,6).toString()+"','"+
                                    tabMode.getValueAt(r,7).toString()+"','"+
                                    tabMode.getValueAt(r,8).toString()+"','"+
                                    tabMode.getValueAt(r,9).toString()+"','"+
                                    tabMode.getValueAt(r,10).toString()+"','"+
                                    tabMode.getValueAt(r,11).toString()+"','"+
                                    tabMode.getValueAt(r,12).toString()+"','','','','','','','','','','','','','','','','','','','','','','','','"+akses.getalamatip()+"'","Rekap Nota Pembayaran");
                }                    
            }
               
            Valid.MyReportqry("rptRl32.jasper","report","::[ Formulir RL 3.2 ]::","select * from temporary where temporary.temp37='"+akses.getalamatip()+"' order by temporary.no",param);
        }
        this.setCursor(Cursor.getDefaultCursor());
}//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnPrintActionPerformed(null);
        }else{
            //Valid.pindah(evt, BtnHapus, BtnAll);
        }
}//GEN-LAST:event_BtnPrintKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }else{Valid.pindah(evt,BtnKeluar,TCari);}
}//GEN-LAST:event_BtnKeluarKeyPressed

private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
       runBackground(() ->tampil());
}//GEN-LAST:event_BtnCariActionPerformed

private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR)); 
            runBackground(() ->tampil());
            this.setCursor(Cursor.getDefaultCursor());
        }else{
            Valid.pindah(evt, TCari, BtnPrint);
        }
}//GEN-LAST:event_BtnCariKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        runBackground(() ->tampil());
    }//GEN-LAST:event_formWindowOpened

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnCariActionPerformed(null);
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_DOWN){
            BtnCari.requestFocus();
        }else if(evt.getKeyCode()==KeyEvent.VK_PAGE_UP){
            BtnKeluar.requestFocus();
        }
    }//GEN-LAST:event_TCariKeyPressed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
           TCari.setText("");
           runBackground(() ->tampil());
    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnAllActionPerformed(null);
        }else{
            
        }
    }//GEN-LAST:event_BtnAllKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(koneksiDB.CARICEPAT().equals("aktif")){
            TCari.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
                @Override
                public void insertUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        runBackground(() ->tampil());
                    }
                }
                @Override
                public void removeUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        runBackground(() ->tampil());
                    }
                }
                @Override
                public void changedUpdate(DocumentEvent e) {
                    if(TCari.getText().length()>2){
                        runBackground(() ->tampil());
                    }
                }
            });
        }
    }//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgRl32 dialog = new DlgRl32(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAll;
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.ScrollPane Scroll;
    private widget.TextBox TCari;
    private widget.Tanggal Tgl1;
    private widget.Tanggal Tgl2;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel6;
    private widget.Label jLabel7;
    private widget.Label label11;
    private widget.Label label18;
    private widget.panelisi panelGlass5;
    private widget.Table tbBangsal;
    // End of variables declaration//GEN-END:variables

    public void tampil(){
        try{
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            Valid.tabelKosong(tabMode);
            String tgl1 = Valid.SetTgl(Tgl1.getSelectedItem()+"");
            String tgl2 = Valid.SetTgl(Tgl2.getSelectedItem()+"");

            // Filter dasar kasus bedah (diagnosa utama S%, T%, atau bedah non trauma K35-K81)
            String bedahDiagnosa =
                    "AND reg_periksa.no_rawat IN (SELECT no_rawat FROM diagnosa_pasien WHERE " +
                    "(kd_penyakit LIKE 'S%' OR kd_penyakit LIKE 'T%' " +
                    "OR kd_penyakit LIKE 'K35%' OR kd_penyakit LIKE 'K36%' OR kd_penyakit LIKE 'K37%' OR kd_penyakit LIKE 'K38%' " +
                    "OR kd_penyakit LIKE 'K40%' OR kd_penyakit LIKE 'K41%' OR kd_penyakit LIKE 'K42%' OR kd_penyakit LIKE 'K43%' OR kd_penyakit LIKE 'K44%' OR kd_penyakit LIKE 'K45%' OR kd_penyakit LIKE 'K46%' " +
                    "OR kd_penyakit LIKE 'K56%' OR kd_penyakit LIKE 'K80%' OR kd_penyakit LIKE 'K81%') " +
                    "AND prioritas=1)";

            // [nama, kondisi WHERE tambahan untuk filter jenis kasus]
            // Kasus bedah dipilah menurut macam kasus pada data triase IGD
            java.util.List<String[]> kasusTypes = new java.util.ArrayList<>();
            ps = koneksi.prepareStatement("SELECT kode_kasus, macam_kasus FROM master_triase_macam_kasus ORDER BY kode_kasus");
            rs = ps.executeQuery();
            while(rs.next()){
                kasusTypes.add(new String[]{"Bedah - "+rs.getString("macam_kasus"),
                    bedahDiagnosa +
                    " AND reg_periksa.no_rawat IN (SELECT no_rawat FROM data_triase_igd WHERE kode_kasus='"+rs.getString("kode_kasus")+"')"});
            }
            rs.close();
            ps.close();
            kasusTypes.add(new String[]{"Bedah - Belum Ada Data Triase",
                bedahDiagnosa +
                " AND reg_periksa.no_rawat NOT IN (SELECT no_rawat FROM data_triase_igd)"});
            kasusTypes.add(new String[]{"Non Bedah",
                    "AND TIMESTAMPDIFF(YEAR,pasien.tgl_lahir,reg_periksa.tgl_registrasi) >= 14 " +
                    "AND TIMESTAMPDIFF(YEAR,pasien.tgl_lahir,reg_periksa.tgl_registrasi) < 60 " +
                    "AND reg_periksa.no_rawat NOT IN (SELECT no_rawat FROM diagnosa_pasien WHERE " +
                    "(kd_penyakit LIKE 'S%' OR kd_penyakit LIKE 'T%' " +
                    "OR kd_penyakit LIKE 'K35%' OR kd_penyakit LIKE 'K36%' OR kd_penyakit LIKE 'K37%' OR kd_penyakit LIKE 'K38%' " +
                    "OR kd_penyakit LIKE 'K40%' OR kd_penyakit LIKE 'K41%' OR kd_penyakit LIKE 'K42%' OR kd_penyakit LIKE 'K43%' OR kd_penyakit LIKE 'K44%' OR kd_penyakit LIKE 'K45%' OR kd_penyakit LIKE 'K46%' " +
                    "OR kd_penyakit LIKE 'K56%' OR kd_penyakit LIKE 'K80%' OR kd_penyakit LIKE 'K81%') " +
                    "AND prioritas=1) " +
                    "AND reg_periksa.no_rawat NOT IN (SELECT no_rawat FROM diagnosa_pasien WHERE kd_penyakit LIKE 'F%' AND prioritas=1) " +
                    "AND reg_periksa.no_rawat NOT IN (SELECT no_rawat FROM diagnosa_pasien WHERE (kd_penyakit LIKE 'O%' OR kd_penyakit LIKE 'Z3%') AND prioritas=1)"});
            kasusTypes.add(new String[]{"Jiwa",
                    "AND reg_periksa.no_rawat IN (SELECT no_rawat FROM diagnosa_pasien WHERE kd_penyakit LIKE 'F%' AND prioritas=1)"});
            kasusTypes.add(new String[]{"Anak",
                    "AND TIMESTAMPDIFF(YEAR,pasien.tgl_lahir,reg_periksa.tgl_registrasi) BETWEEN 1 AND 13"});
            kasusTypes.add(new String[]{"Kebidanan",
                    "AND reg_periksa.no_rawat IN (SELECT no_rawat FROM diagnosa_pasien WHERE (kd_penyakit LIKE 'O%' OR kd_penyakit LIKE 'Z3%') AND prioritas=1)"});
            kasusTypes.add(new String[]{"Geriatri",
                    "AND TIMESTAMPDIFF(YEAR,pasien.tgl_lahir,reg_periksa.tgl_registrasi) >= 60"});
            kasusTypes.add(new String[]{"Bayi",
                    "AND TIMESTAMPDIFF(YEAR,pasien.tgl_lahir,reg_periksa.tgl_registrasi) < 1"});

            // Mati di IGD = meninggal di rumah sakit, DOA = datang sudah meninggal (tempat meninggal di luar RS)
            String tempatMatiIGD = " AND (pasien_mati.temp_meninggal IS NULL OR pasien_mati.temp_meninggal IN ('-','Rumah Sakit'))";
            String tempatDOA = " AND pasien_mati.temp_meninggal IN ('Puskesmas','Rumah Bersalin','Rumah Tempat Tinggal','Lain-lain (Termasuk Doa)','Tidak tahu')";

            // Luka-luka = pasien kasus bedah dengan diagnosa utama cedera (S/T) yang masih hidup
            String lukaFilter = " AND reg_periksa.no_rawat IN (SELECT no_rawat FROM diagnosa_pasien WHERE " +
                    "(kd_penyakit LIKE 'S%' OR kd_penyakit LIKE 'T%') AND prioritas=1)" +
                    " AND reg_periksa.no_rkm_medis NOT IN (SELECT no_rkm_medis FROM pasien_mati)";

            i=1;
            ttlrujukan=0;ttlnonrujukan=0;ttldirawat=0;
            ttldirujuk=0;ttlpulang=0;
            ttlmeninggalL=0;ttlmeninggalP=0;ttldoaL=0;ttldoaP=0;
            ttllukaL=0;ttllukaP=0;

            for(String[] kasus : kasusTypes){
                String nmKasus  = kasus[0];
                String kasusFilter = kasus[1];

                String baseFrom = "FROM reg_periksa " +
                    "INNER JOIN pasien ON pasien.no_rkm_medis=reg_periksa.no_rkm_medis ";
                String baseWhere = "WHERE reg_periksa.kd_poli='IGDK' " +
                    "AND reg_periksa.tgl_registrasi BETWEEN '"+tgl1+"' AND '"+tgl2+"' " +
                    kasusFilter;

                rujukan = Sequel.cariInteger(
                    "SELECT COUNT(DISTINCT reg_periksa.no_rawat) " + baseFrom +
                    "INNER JOIN rujuk_masuk ON rujuk_masuk.no_rawat=reg_periksa.no_rawat " +
                    baseWhere);

                nonrujukan = Sequel.cariInteger(
                    "SELECT COUNT(DISTINCT reg_periksa.no_rawat) " + baseFrom + baseWhere +
                    " AND reg_periksa.no_rawat NOT IN (SELECT no_rawat FROM rujuk_masuk)");

                dirawat = Sequel.cariInteger(
                    "SELECT COUNT(DISTINCT reg_periksa.no_rawat) " + baseFrom +
                    "INNER JOIN kamar_inap ON kamar_inap.no_rawat=reg_periksa.no_rawat " +
                    baseWhere);

                dirujuk = Sequel.cariInteger(
                    "SELECT COUNT(DISTINCT reg_periksa.no_rawat) " + baseFrom +
                    "INNER JOIN rujuk ON rujuk.no_rawat=reg_periksa.no_rawat " +
                    baseWhere);

                meninggalL = Sequel.cariInteger(
                    "SELECT COUNT(DISTINCT reg_periksa.no_rawat) " + baseFrom +
                    "INNER JOIN pasien_mati ON pasien_mati.no_rkm_medis=reg_periksa.no_rkm_medis " +
                    baseWhere + " AND pasien.jk='L'" + tempatMatiIGD);

                meninggalP = Sequel.cariInteger(
                    "SELECT COUNT(DISTINCT reg_periksa.no_rawat) " + baseFrom +
                    "INNER JOIN pasien_mati ON pasien_mati.no_rkm_medis=reg_periksa.no_rkm_medis " +
                    baseWhere + " AND pasien.jk='P'" + tempatMatiIGD);

                doaL = Sequel.cariInteger(
                    "SELECT COUNT(DISTINCT reg_periksa.no_rawat) " + baseFrom +
                    "INNER JOIN pasien_mati ON pasien_mati.no_rkm_medis=reg_periksa.no_rkm_medis " +
                    baseWhere + " AND pasien.jk='L'" + tempatDOA);

                doaP = Sequel.cariInteger(
                    "SELECT COUNT(DISTINCT reg_periksa.no_rawat) " + baseFrom +
                    "INNER JOIN pasien_mati ON pasien_mati.no_rkm_medis=reg_periksa.no_rkm_medis " +
                    baseWhere + " AND pasien.jk='P'" + tempatDOA);

                if(nmKasus.startsWith("Bedah")){
                    lukaL = Sequel.cariInteger(
                        "SELECT COUNT(DISTINCT reg_periksa.no_rawat) " + baseFrom + baseWhere +
                        " AND pasien.jk='L'" + lukaFilter);
                    lukaP = Sequel.cariInteger(
                        "SELECT COUNT(DISTINCT reg_periksa.no_rawat) " + baseFrom + baseWhere +
                        " AND pasien.jk='P'" + lukaFilter);
                }else{
                    lukaL = 0;
                    lukaP = 0;
                }

                pulang = Sequel.cariInteger(
                    "SELECT COUNT(DISTINCT reg_periksa.no_rawat) " + baseFrom + baseWhere +
                    " AND reg_periksa.no_rawat NOT IN (SELECT no_rawat FROM kamar_inap) " +
                    "AND reg_periksa.no_rawat NOT IN (SELECT no_rawat FROM rujuk) " +
                    "AND reg_periksa.no_rkm_medis NOT IN (SELECT no_rkm_medis FROM pasien_mati)");

                ttlrujukan+=rujukan;ttlnonrujukan+=nonrujukan;ttldirawat+=dirawat;
                ttldirujuk+=dirujuk;ttlpulang+=pulang;
                ttlmeninggalL+=meninggalL;ttlmeninggalP+=meninggalP;ttldoaL+=doaL;ttldoaP+=doaP;
                ttllukaL+=lukaL;ttllukaP+=lukaP;
                tabMode.addRow(new Object[]{
                    i, nmKasus, rujukan, nonrujukan, dirawat, dirujuk, pulang, lukaL, lukaP, meninggalL, meninggalP, doaL, doaP
                });
                i++;
            }
            tabMode.addRow(new Object[]{
                ">>","TOTAL",
                ttlrujukan,ttlnonrujukan,ttldirawat,ttldirujuk,ttlpulang,ttllukaL,ttllukaP,ttlmeninggalL,ttlmeninggalP,ttldoaL,ttldoaP
            });
            this.setCursor(Cursor.getDefaultCursor());
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
    }

    private void runBackground(Runnable task) {
        if (ceksukses) return;
        if (executor.isShutdown() || executor.isTerminated()) return;
        if (!isDisplayable()) return;

        ceksukses = true;
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        try {
            executor.submit(() -> {
                try {
                    task.run();
                } finally {
                    ceksukses = false;
                    SwingUtilities.invokeLater(() -> {
                        if (isDisplayable()) {
                            setCursor(Cursor.getDefaultCursor());
                        }
                    });
                }
            });
        } catch (RejectedExecutionException ex) {
            ceksukses = false;
        }
    }
    
    @Override
    public void dispose() {
        executor.shutdownNow();
        super.dispose();
    }
}
