/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khanzacetakantrianloket;

import fungsi.akses;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Timer;

/**
 *
 * @author windiartonugroho
 */
public class frmUtama1 extends javax.swing.JFrame {
    private final Connection koneksi=koneksiDB.condb();
    private final validasi Valid=new validasi();
    private final sekuel Sequel=new sekuel();
    private PreparedStatement ps;
    private ResultSet rs;
    /**
     * Creates new form frmUtama
     */
    public frmUtama1() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        jam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelTengah = new widget.Panel();
        LabelNonBPJS = new widget.Label();
        LabelA = new widget.Label();
        LabelNomorA = new widget.Label();
        btnCetakA = new widget.Button();
        LabelNonBPJS1 = new widget.Label();
        LabelNomorB = new widget.Label();
        LabelB = new widget.Label();
        btnCetakB = new widget.Button();
        panelAtas = new widget.Panel();
        LabelTanggal = new widget.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMKES Khanza Cetak Antrian Loket");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setLayout(new java.awt.BorderLayout());

        panelTengah.setPreferredSize(new java.awt.Dimension(496, 47));

        LabelNonBPJS.setForeground(new java.awt.Color(153, 255, 255));
        LabelNonBPJS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNonBPJS.setText("NON BPJS");
        LabelNonBPJS.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        LabelA.setForeground(new java.awt.Color(51, 0, 255));
        LabelA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelA.setText("A");
        LabelA.setFont(new java.awt.Font("Tahoma", 0, 350)); // NOI18N

        LabelNomorA.setForeground(new java.awt.Color(51, 51, 255));
        LabelNomorA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNomorA.setText("001");
        LabelNomorA.setFont(new java.awt.Font("Tahoma", 0, 350)); // NOI18N

        btnCetakA.setForeground(new java.awt.Color(255, 255, 51));
        btnCetakA.setText("Cetak");
        btnCetakA.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        btnCetakA.setGlassColor(new java.awt.Color(255, 255, 204));
        btnCetakA.setPreferredSize(new java.awt.Dimension(158, 125));
        btnCetakA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakAActionPerformed(evt);
            }
        });

        LabelNonBPJS1.setForeground(new java.awt.Color(153, 255, 255));
        LabelNonBPJS1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNonBPJS1.setText("BPJS");
        LabelNonBPJS1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N

        LabelNomorB.setForeground(new java.awt.Color(51, 51, 255));
        LabelNomorB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNomorB.setText("001");
        LabelNomorB.setFont(new java.awt.Font("Tahoma", 0, 350)); // NOI18N

        LabelB.setForeground(new java.awt.Color(51, 0, 255));
        LabelB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelB.setText("B");
        LabelB.setFont(new java.awt.Font("Tahoma", 0, 350)); // NOI18N

        btnCetakB.setForeground(new java.awt.Color(255, 255, 51));
        btnCetakB.setText("Cetak");
        btnCetakB.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        btnCetakB.setGlassColor(new java.awt.Color(255, 255, 204));
        btnCetakB.setPreferredSize(new java.awt.Dimension(158, 125));
        btnCetakB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTengahLayout = new javax.swing.GroupLayout(panelTengah);
        panelTengah.setLayout(panelTengahLayout);
        panelTengahLayout.setHorizontalGroup(
            panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTengahLayout.createSequentialGroup()
                .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTengahLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCetakA, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelTengahLayout.createSequentialGroup()
                                .addComponent(LabelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LabelNomorA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelTengahLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelNonBPJS, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTengahLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCetakB, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelTengahLayout.createSequentialGroup()
                                .addComponent(LabelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelNomorB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(LabelNonBPJS1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelTengahLayout.setVerticalGroup(
            panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTengahLayout.createSequentialGroup()
                .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTengahLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelNonBPJS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNomorA, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelTengahLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(LabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(btnCetakA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTengahLayout.createSequentialGroup()
                        .addComponent(LabelNonBPJS1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelNomorB, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelB, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addComponent(btnCetakB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        internalFrame1.add(panelTengah, java.awt.BorderLayout.CENTER);

        panelAtas.setPreferredSize(new java.awt.Dimension(496, 47));

        LabelTanggal.setForeground(new java.awt.Color(255, 255, 51));
        LabelTanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTanggal.setText("Antrian Loket Pendaftaran Tanggal :");
        LabelTanggal.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N

        javax.swing.GroupLayout panelAtasLayout = new javax.swing.GroupLayout(panelAtas);
        panelAtas.setLayout(panelAtasLayout);
        panelAtasLayout.setHorizontalGroup(
            panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1676, Short.MAX_VALUE)
            .addGroup(panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(LabelTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 1676, Short.MAX_VALUE))
        );
        panelAtasLayout.setVerticalGroup(
            panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
            .addGroup(panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAtasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(LabelTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        internalFrame1.add(panelAtas, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        autonomer();
        try{            
            ps=koneksi.prepareStatement("select nama_instansi, alamat_instansi, kabupaten, propinsi, aktifkan, wallpaper,kontak,email,logo from setting");
            try {
                rs=ps.executeQuery();
                while(rs.next()){
                    akses.setnamars(rs.getString("nama_instansi"));
                    akses.setalamatrs(rs.getString("alamat_instansi"));
                    akses.setkabupatenrs(rs.getString("kabupaten"));
                    akses.setpropinsirs(rs.getString("propinsi"));
                    akses.setkontakrs(rs.getString("kontak"));
                    akses.setemailrs(rs.getString("email"));
                }  
            } catch (Exception e) {
                System.out.println(e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
                if(ps!=null){
                    ps.close();
                }
            }                 
        }catch(Exception e){
            System.out.println("Notifikasi : Silahkan Set Aplikasi "+e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnCetakAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakAActionPerformed
        // if(Sequel.menyimpantf("antripendaftaran_nomor","current_date(),current_time(),'"+LabelNomor.getText()+"','00:00:00','-'","Nomor Antrian")==true){

            if(Sequel.menyimpantf("antripendaftaran_nomor","'"+LabelA.getText()+"','"+LabelNomorA.getText()+"','0',concat(current_date(),' ',current_time()),''","Nomor Antrian")==true){
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                Map<String, Object> param = new HashMap<>();
                param.put("namars",akses.getnamars());
                param.put("alamatrs",akses.getalamatrs());
                param.put("kotars",akses.getkabupatenrs());
                param.put("propinsirs",akses.getpropinsirs());
                param.put("kontakrs",akses.getkontakrs());
                param.put("emailrs",akses.getemailrs());
                Valid.MyReportqry("rptAntriLoket.jasper","report","::[ Antrian Loket ]::",
                    "select antripendaftaran_nomor.jam,antripendaftaran_nomor.nomor from antripendaftaran_nomor where LEFT(antripendaftaran_nomor.jam,10)=current_date and antripendaftaran_nomor.nomor='"+LabelNomorA.getText()+"' ",param);
                this.setCursor(Cursor.getDefaultCursor());
                autonomer();
            }else{
                autonomer();
                if(Sequel.menyimpantf("antripendaftaran_nomor","'"+LabelA.getText()+"','"+LabelNomorA.getText()+"','0',concat(current_date(),' ',current_time()),''","Nomor Antrian")==true){
                    this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                    Map<String, Object> param = new HashMap<>();
                    param.put("namars",akses.getnamars());
                    param.put("alamatrs",akses.getalamatrs());
                    param.put("kotars",akses.getkabupatenrs());
                    param.put("propinsirs",akses.getpropinsirs());
                    param.put("kontakrs",akses.getkontakrs());
                    param.put("emailrs",akses.getemailrs());
                    Valid.MyReportqry("rptAntriLoket.jasper","report","::[ Antrian Loket ]::",
                        "select antripendaftaran_nomor.jam,antripendaftaran_nomor.nomor from antripendaftaran_nomor where LEFT(antripendaftaran_nomor.jam,10)=current_date and antripendaftaran_nomor.nomor='"+LabelNomorA.getText()+"' ",param);
                    this.setCursor(Cursor.getDefaultCursor());
                    autonomer();
                }else{
                    autonomer();
                    if(Sequel.menyimpantf("antripendaftaran_nomor","'"+LabelA.getText()+"','"+LabelNomorA.getText()+"','0',concat(current_date(),' ',current_time()),''","Nomor Antrian")==true){
                        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                        Map<String, Object> param = new HashMap<>();
                        param.put("namars",akses.getnamars());
                        param.put("alamatrs",akses.getalamatrs());
                        param.put("kotars",akses.getkabupatenrs());
                        param.put("propinsirs",akses.getpropinsirs());
                        param.put("kontakrs",akses.getkontakrs());
                        param.put("emailrs",akses.getemailrs());
                        Valid.MyReportqry("rptAntriLoket.jasper","report","::[ Antrian Loket ]::",
                            "select antripendaftaran_nomor.jam,antripendaftaran_nomor.nomor from antripendaftaran_nomor where LEFT(antripendaftaran_nomor.jam,10)=current_date and antripendaftaran_nomor.nomor='"+LabelNomorA.getText()+"' ",param);
                        this.setCursor(Cursor.getDefaultCursor());
                        autonomer();
                    }
                }
            }
            /*    this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            cetakAntrianHuruf("A");
            this.setCursor(Cursor.getDefaultCursor());*/
    }//GEN-LAST:event_btnCetakAActionPerformed

    private void btnCetakBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakBActionPerformed
              // if(Sequel.menyimpantf("antripendaftaran_nomor","current_date(),current_time(),'"+LabelNomor.getText()+"','00:00:00','-'","Nomor Antrian")==true){

            if(Sequel.menyimpantf("antripendaftaran_nomor","'"+LabelB.getText()+"','"+LabelNomorB.getText()+"','0',concat(current_date(),' ',current_time()),''","Nomor Antrian")==true){
                this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                Map<String, Object> param = new HashMap<>();
                param.put("namars",akses.getnamars());
                param.put("alamatrs",akses.getalamatrs());
                param.put("kotars",akses.getkabupatenrs());
                param.put("propinsirs",akses.getpropinsirs());
                param.put("kontakrs",akses.getkontakrs());
                param.put("emailrs",akses.getemailrs());
                Valid.MyReportqry("rptAntriLoket.jasper","report","::[ Antrian Loket ]::",
                    "select antripendaftaran_nomor.jam,antripendaftaran_nomor.nomor from antripendaftaran_nomor where LEFT(antripendaftaran_nomor.jam,10)=current_date and antripendaftaran_nomor.nomor='"+LabelNomorA.getText()+"' ",param);
                this.setCursor(Cursor.getDefaultCursor());
                autonomer2();
            }else{
                autonomer2();
                if(Sequel.menyimpantf("antripendaftaran_nomor","'"+LabelB.getText()+"','"+LabelNomorB.getText()+"','0',concat(current_date(),' ',current_time()),''","Nomor Antrian")==true){
                    this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                    Map<String, Object> param = new HashMap<>();
                    param.put("namars",akses.getnamars());
                    param.put("alamatrs",akses.getalamatrs());
                    param.put("kotars",akses.getkabupatenrs());
                    param.put("propinsirs",akses.getpropinsirs());
                    param.put("kontakrs",akses.getkontakrs());
                    param.put("emailrs",akses.getemailrs());
                    Valid.MyReportqry("rptAntriLoket.jasper","report","::[ Antrian Loket ]::",
                        "select antripendaftaran_nomor.jam,antripendaftaran_nomor.nomor from antripendaftaran_nomor where LEFT(antripendaftaran_nomor.jam,10)=current_date and antripendaftaran_nomor.nomor='"+LabelNomorA.getText()+"' ",param);
                    this.setCursor(Cursor.getDefaultCursor());
                    autonomer2();
                }else{
                    autonomer2();
                    if(Sequel.menyimpantf("antripendaftaran_nomor","'"+LabelB.getText()+"','"+LabelNomorB.getText()+"','0',concat(current_date(),' ',current_time()),''","Nomor Antrian")==true){
                        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                        Map<String, Object> param = new HashMap<>();
                        param.put("namars",akses.getnamars());
                        param.put("alamatrs",akses.getalamatrs());
                        param.put("kotars",akses.getkabupatenrs());
                        param.put("propinsirs",akses.getpropinsirs());
                        param.put("kontakrs",akses.getkontakrs());
                        param.put("emailrs",akses.getemailrs());
                        Valid.MyReportqry("rptAntriLoket.jasper","report","::[ Antrian Loket ]::",
                            "select antripendaftaran_nomor.jam,antripendaftaran_nomor.nomor from antripendaftaran_nomor where LEFT(antripendaftaran_nomor.jam,10)=current_date and antripendaftaran_nomor.nomor='"+LabelNomorA.getText()+"' ",param);
                        this.setCursor(Cursor.getDefaultCursor());
                        autonomer2();
                    }
                }
            }
    }//GEN-LAST:event_btnCetakBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUtama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUtama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUtama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUtama1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUtama1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Label LabelA;
    private widget.Label LabelB;
    private widget.Label LabelNomorA;
    private widget.Label LabelNomorB;
    private widget.Label LabelNonBPJS;
    private widget.Label LabelNonBPJS1;
    private widget.Label LabelTanggal;
    private widget.Button btnCetakA;
    private widget.Button btnCetakB;
    private widget.InternalFrame internalFrame1;
    private widget.Panel panelAtas;
    private widget.Panel panelTengah;
    // End of variables declaration//GEN-END:variables
    private void jam(){
        ActionListener taskPerformer = new ActionListener(){
            private int nilai_jam;
            private int nilai_menit;
            private int nilai_detik;
            public void actionPerformed(ActionEvent e) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                Date now = Calendar.getInstance().getTime();
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");  
                LocalDateTime sekarang = LocalDateTime.now();  
                LabelTanggal.setText("Antrian Loket Pendaftaran Tanggal : "+dtf.format(sekarang)); 
                // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
                nilai_jam = now.getHours();
                nilai_menit = now.getMinutes();
                nilai_detik = now.getSeconds();
                // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
                if (nilai_jam <= 9) {
                    // Tambahkan "0" didepannya
                    nol_jam = "0";
                }
                // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
                if (nilai_menit <= 9) {
                    // Tambahkan "0" didepannya
                    nol_menit = "0";
                }
                // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
                if (nilai_detik <= 9) {
                    // Tambahkan "0" didepannya
                    nol_detik = "0";
                }
                // Membuat String JAM, MENIT, DETIK
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                if(menit.equals("01")&&detik.equals("01")){
                    autonomer();
                }
            }
        };
        // Timer
        new Timer(1000, taskPerformer).start();
    }
    
    private void autonomer(){
        Valid.autoNomer3("select ifnull(MAX(CONVERT(antripendaftaran_nomor.nomor,signed)),0) from antripendaftaran_nomor where LEFT(antripendaftaran_nomor.jam,10)=current_date() and prefix='A' ","",1,LabelNomorA);
    }
    
    private void autonomer2(){
        Valid.autoNomer3("select ifnull(MAX(CONVERT(antripendaftaran_nomor.nomor,signed)),0) from antripendaftaran_nomor where LEFT(antripendaftaran_nomor.jam,10)=current_date() and prefix='B'","",1,LabelNomorB);
    }
    
    
    
    private void cetakAntrianHuruf(String prefix) {
    /*    switch (prefix) {
            case "A":
                if (Sequel.executeRawSmc(
                    "insert into antriloketcetak_smc (nomor, tanggal, jam) values (concat('A', lpad(?, greatest(length(substring(nomor, 2)), 3), '0')), current_date(), current_time())",
                    String.valueOf(Integer.parseInt(HurufA.getText().substring(HurufA.getText().indexOf("(") + 2, HurufA.getText().length() - 1)) + 1)
                )) {
                    param.put("logo", Sequel.cariGambar("select logo from setting"));
                    Valid.printReportSmc("rptAntriLoketAPM.jasper", "report", "::[ Antrian Loket ]::", param, koneksiDB.PRINTER_ANTRIAN(), 1,
                        "select date_format(tanggal, '%d-%m-%Y') as tanggal, max(nomor) as nomor, " +
                        "jam from antriloketcetak_smc where left(nomor, 1) = 'A' and tanggal = current_date()");
                }
                break;
            case "B":
                if (Sequel.executeRawSmc(
                    "insert into antriloketcetak_smc (nomor, tanggal, jam) values (concat('B', lpad(?, greatest(length(substring(nomor, 2)), 3), '0')), current_date(), current_time())",
                    String.valueOf(Integer.parseInt(HurufB.getText().substring(HurufB.getText().indexOf("(") + 2, HurufB.getText().length() - 1)) + 1)
                )) {
                    param.put("logo", Sequel.cariGambar("select logo from setting"));
                    Valid.printReportSmc("rptAntriLoketAPM.jasper", "report", "::[ Antrian Loket ]::", param, koneksiDB.PRINTER_ANTRIAN(), 1,
                        "select date_format(tanggal, '%d-%m-%Y') as tanggal, max(nomor) as nomor, " +
                        "jam from antriloketcetak_smc where left(nomor, 1) = 'B' and tanggal = current_date()");
                }
                break;            
        }
        tampil();*/
    }
}
