-- Tabel Catatan Keperawatan Intra Operasi (RM 22.OK-02.02 + balutan/spesimen RM 22.OK-02.03)
-- Diisi oleh staf perawat ruang operasi, satu catatan per no_rawat
CREATE TABLE IF NOT EXISTS `catatan_keperawatan_intra_operasi` (
  `no_rawat` varchar(17) NOT NULL,
  `tanggal` datetime NOT NULL,
  `jam_mulai` varchar(8) NOT NULL DEFAULT '',
  `jam_selesai` varchar(8) NOT NULL DEFAULT '',
  `tindakan_operasi` varchar(200) NOT NULL DEFAULT '',
  `tipe_operasi` varchar(30) NOT NULL DEFAULT '',
  `tipe_pembiusan` varchar(30) NOT NULL DEFAULT '',
  `gcs_e` varchar(5) NOT NULL DEFAULT '',
  `gcs_m` varchar(5) NOT NULL DEFAULT '',
  `gcs_v` varchar(5) NOT NULL DEFAULT '',
  `status_emosi` varchar(30) NOT NULL DEFAULT '',
  `posisi_kanula` varchar(50) NOT NULL DEFAULT '',
  `kanula_ket` varchar(100) NOT NULL DEFAULT '',
  `posisi_operasi` varchar(50) NOT NULL DEFAULT '',
  `posisi_diawasi` varchar(100) NOT NULL DEFAULT '',
  `risiko_luka_tekan` varchar(20) NOT NULL DEFAULT '',
  `skor_braden` varchar(20) NOT NULL DEFAULT '',
  `stocking_vte` varchar(10) NOT NULL DEFAULT '',
  `posisi_lengan` varchar(50) NOT NULL DEFAULT '',
  `alat_bantu` varchar(60) NOT NULL DEFAULT '',
  `kateter` varchar(40) NOT NULL DEFAULT '',
  `kateter_oleh` varchar(100) NOT NULL DEFAULT '',
  `jenis_kateter` varchar(60) NOT NULL DEFAULT '',
  `no_kateter` varchar(15) NOT NULL DEFAULT '',
  `isi_balon` varchar(15) NOT NULL DEFAULT '',
  `kateter_arah` varchar(40) NOT NULL DEFAULT '',
  `kateter_traksi` varchar(10) NOT NULL DEFAULT '',
  `persiapan_kulit` varchar(60) NOT NULL DEFAULT '',
  `persiapan_kulit_ket` varchar(100) NOT NULL DEFAULT '',
  `diathermy` varchar(30) NOT NULL DEFAULT '',
  `elektroda_lokasi` varchar(40) NOT NULL DEFAULT '',
  `elektroda_oleh` varchar(100) NOT NULL DEFAULT '',
  `kulit_sebelum` varchar(30) NOT NULL DEFAULT '',
  `kulit_sesudah` varchar(30) NOT NULL DEFAULT '',
  `kode_elektrosurgical` varchar(50) NOT NULL DEFAULT '',
  `unit_pemanas` varchar(10) NOT NULL DEFAULT '',
  `suhu_pemanas` varchar(15) NOT NULL DEFAULT '',
  `torniket_oleh` varchar(100) NOT NULL DEFAULT '',
  `tor_lka_mulai` varchar(8) NOT NULL DEFAULT '',
  `tor_lka_selesai` varchar(8) NOT NULL DEFAULT '',
  `tor_lka_tekanan` varchar(15) NOT NULL DEFAULT '',
  `tor_lki_mulai` varchar(8) NOT NULL DEFAULT '',
  `tor_lki_selesai` varchar(8) NOT NULL DEFAULT '',
  `tor_lki_tekanan` varchar(15) NOT NULL DEFAULT '',
  `tor_pka_mulai` varchar(8) NOT NULL DEFAULT '',
  `tor_pka_selesai` varchar(8) NOT NULL DEFAULT '',
  `tor_pka_tekanan` varchar(15) NOT NULL DEFAULT '',
  `tor_pki_mulai` varchar(8) NOT NULL DEFAULT '',
  `tor_pki_selesai` varchar(8) NOT NULL DEFAULT '',
  `tor_pki_tekanan` varchar(15) NOT NULL DEFAULT '',
  `laser` varchar(10) NOT NULL DEFAULT '',
  `laser_diawasi` varchar(100) NOT NULL DEFAULT '',
  `implant` varchar(300) NOT NULL DEFAULT '',
  `drain` varchar(10) NOT NULL DEFAULT '',
  `jenis_drain` varchar(100) NOT NULL DEFAULT '',
  `sifat_drain` varchar(20) NOT NULL DEFAULT '',
  `cairan_glycine` varchar(15) NOT NULL DEFAULT '',
  `cairan_wfi` varchar(15) NOT NULL DEFAULT '',
  `cairan_nacl` varchar(15) NOT NULL DEFAULT '',
  `cairan_bss` varchar(15) NOT NULL DEFAULT '',
  `cairan_lain` varchar(100) NOT NULL DEFAULT '',
  `balutan` varchar(10) NOT NULL DEFAULT '',
  `jenis_balutan` varchar(100) NOT NULL DEFAULT '',
  `spesimen` varchar(30) NOT NULL DEFAULT '',
  `spesimen_ket` varchar(200) NOT NULL DEFAULT '',
  `jumlah_total_jaringan` varchar(100) NOT NULL DEFAULT '',
  `spesimen_diberikan` varchar(10) NOT NULL DEFAULT '',
  `jenis_jaringan` varchar(100) NOT NULL DEFAULT '',
  `jumlah_jaringan` varchar(60) NOT NULL DEFAULT '',
  `nama_penerima` varchar(100) NOT NULL DEFAULT '',
  `keterangan` varchar(400) NOT NULL DEFAULT '',
  `perawat_steril` varchar(100) NOT NULL DEFAULT '',
  `perawat_sirkuler` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`no_rawat`),
  KEY `tanggal` (`tanggal`)
) ENGINE=InnoDB;
